### ISSUE TITLE
ガラケーのサポートを終了する

### ISSUE THREAD

**Issue by koushin-ru** [PrefKarafuto/ex0ch#50]
ガラケーのサポートを終了すべきか意見を伺いたいです。

理由：
- コードベースの簡素化

必要な作業：
- 書き込み時にガラケーを判定するモジュールの削除
  - test/cidr_list.pl (ファイルごと)
  - test/data_utils.pl の GetClient 関数
  - test/constant.pl のガラケー関連の定数の削除
- 携帯用バナーなどの削除
- 管理画面から携帯からのスレッド作成を許可する機能の削除
- その他（教えてください）

**Comment by PrefKarafuto** [comment]
ガラケーのサポートは終了する方向で動いており、すでにr.cgi,p.cgi等や一部関連コードは削除されています。
しかし、ご指摘の通り完全ではありませんので、それらの箇所も削除していくことになろうかと思います
