### ISSUE TITLE
ﾜｯﾁｮｲのIPv6対応

### ISSUE THREAD

**Issue by frictionsmooth** [PrefKarafuto/ex0ch#56]
現在IPv6が増えていて今のﾜｯﾁｮｲのままだとｱﾝﾀﾀﾞﾚだらけになってしまうので対応する必要があると思います。

**Comment by PrefKarafuto** [comment]
0ch+にIPv6対応の逆引き関数がなかったので、data_utils.plにreverse_lookup関数を追加しました
