### ISSUE TITLE
管理画面でのスレタイ変更、スレ情報更新の実装

### ISSUE THREAD

**Issue by frictionsmooth** [PrefKarafuto/ex0ch#63]
タイトルの通り管理画面でスレタイの変更とスレ情報の更新を実装するのはどうでしょうか。
現状スレタイを変更するには手動でdatとsubject.txtの書き換えをする必要があり、なかなかの手間です。
そして管理画面でレスを書き換えた場合、内容を反映させるのに同板の適当なスレに何かレスする必要があり、これも手間がかかります。
特にスレタイ変更に関しては使用頻度がなかなか高いと思いますので、管理画面だけで完結出来たらとても助かります。

**Comment by PrefKarafuto** [comment]
レス編集画面から、>>1のレスを選択するとスレタイを編集できるようにしました

**Comment by PrefKarafuto** [comment]
管理画面からのスレタイ・スレッド属性変更機能を追加完了しました
