### ISSUE TITLE
開発者向けにレス情報を取得、変更するモジュールの追加

### ISSUE THREAD

**Issue by frictionsmooth** [PrefKarafuto/ex0ch#64]
タイトルの通りですが
`my $Message = RES_MANAGER::MESSAGE($板名, $スレッドID, レス番号);` 
`my $Message = RES_MANAGER::EDITMESSAGE($板名, $スレッドID, レス番号, $変更後のレス本文);` 
のような形でレス情報を取得しやすくなれば開発している側としては助かります。

**Comment by PrefKarafuto** [comment]
dat.plにGet関数がありますが、それでは不足でしょうか
