### ISSUE TITLE
デフォルト看板画像の変更について

### ISSUE THREAD

**Issue by PrefKarafuto** [PrefKarafuto/ex0ch#7]
新しい看板画像をTwitterで募集して、プロジェクトに人を呼び込みたいと思うのですが、どうでしょうか。

**Comment by goodpotatosystems** [comment]
twitterアカウントは新規に作る感じですか？

**Comment by PrefKarafuto** [comment]
いえ、Twitter教徒から募るか、若しくはきまぐれ新聞で募集広告を打つことを考えています。

**Comment by goodpotatosystems** [comment]
了解しました。  
芸術芋ならtwitterやってそうですし、よいと思います。
