### ISSUE TITLE
メール欄は廃止してコマンド専用にするのはどうか

### ISSUE THREAD

**Issue by frictionsmooth** [PrefKarafuto/ex0ch#74]
これには賛否あると思いますがプライバシー保護、誤爆防止、利用者の数を鑑みると廃止したほうがいいのではないかと思います。
互換性とsageなどに利用することがある為完全廃止はまず無理だと思いますが、特定のコマンド以外はプラグインも含め全ての処理が終わった後、メール欄は空に置き換えてもいいかもしれません。
その場合は置き換えると不都合な文字列を正規表現で除外できる仕組みにしていただけると助かります。

**Comment by PrefKarafuto** [comment]
とりあえずは互換性の問題もあるので、”メール欄”という表記は止めて”コマンド欄”として残す方向で行きます
あそこにガチメルアド入れてるの、初心者か海外のスパム以外で見たこと無いので
